name: Print

on:
  push:
    branches: [ "main" ]
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: |
          echo "github.head_ref ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}""
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.run_attempt: ${{ github.run_attempt }}"
          echo "actor ${{ github.actor }} ${{ github.actor_id }}"

