name: GitHub Pages Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install

      - name: Build
        run: yarn prod
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: github-pages
          path: dist
          if-no-files-found: error # optional, default is warn

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
        with:
          token: ${{ github.token }}
          artifact_name: github-pages # optional, default is github-pages
