name: 'Run Tests'

on:
  pull_request:

run-name: Testing branch ${{ github.head_ref }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Actor:  ${{ github.actor }}"
          echo "${{ toJson(github)}}"
          echo "========================"
          echo ${{ toJson(inputs) }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: Run unit tests
        run: yarn test
