name: 'Run Tests'

on:
  pull_request:

run-name: Testing branch ${{ github.head_ref }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: |
          echo "Branch:        ${{ github.head_ref }}"
          echo "Actor:         ${{ github.actor }}"
          echo "Triggered by:  ${{ github.triggering_actor }}"
          echo "MR URL:        ${{ github.event.pull_request.html_url }}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: Run unit tests
        run: yarn test
